
#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
# https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
# Set to true enable resizing windows by clicking and dragging on borders and gaps
# Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on


general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(cba6f7ee) rgba(89b4faee) 45deg
    col.inactive_border = rgba(31324488)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 20
    rounding_power = 2

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 2
        vibrancy = 0.1696
    }
}
